### ISSUE TITLE
M1 support

### ISSUE THREAD

**Issue by electr1fy0** [david-kuehn/casita#7]
Please bring native Apple Silicon support to the app.

**Comment by david-kuehn** [comment]
Sorry for the delay on this. After the latest batch of changes, the app is now running on my M1 Air. Despite this, it's still designated as an "Intel" application when viewed in Activity Monitor. Will continue to investigate. Thanks for your patience!

**Comment by david-kuehn** [comment]
Native support for M1 Macs added in [v0.1.5.1](https://github.com/david-kuehn/casita/releases/tag/v0.1.5.1). Binary is now Universal 2 and supports both Apple Silicon & Intel Macs out of the box.
